// Generated by `bun scripts/fontfeatures.ts` — do not edit.
//
// The OpenType features of the faces styles.css bundles, read out of the font files. A stylistic
// set means whatever its own face says it means: ss03 is Arrows in Monaspace Neon, an unrelated
// glyph shape in JetBrains Mono, and in Inter ss05 draws a ring around every capital — so the tag
// alone is never enough to apply, and a face that is not in here has no table we can read.

export interface FaceFeatures {
  /** Every GSUB feature tag the face declares. */
  readonly features: readonly string[];
  /** Stylistic sets and character variants, with the UI name the font gives them. */
  readonly named: readonly { readonly tag: string; readonly name: string }[];
}

export const FACE_FEATURES: Readonly<Record<string, FaceFeatures>> = {
  "Inter": {
    features: ["aalt", "calt", "case", "ccmp", "cv01", "cv02", "cv03", "cv04", "cv05", "cv06", "cv07", "cv08", "cv09", "cv10", "cv11", "cv12", "cv13", "cv14", "dlig", "dnom", "frac", "locl", "numr", "ordn", "pnum", "salt", "sinf", "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "subs", "sups", "tnum", "zero"],
    named: [
      { tag: "cv01", name: "Alternate one" },
      { tag: "cv02", name: "Open four" },
      { tag: "cv03", name: "Open six" },
      { tag: "cv04", name: "Open nine" },
      { tag: "cv05", name: "Lower-case L with tail" },
      { tag: "cv06", name: "Simplified u" },
      { tag: "cv07", name: "Alternate sharp s" },
      { tag: "cv08", name: "Upper-case i with serif" },
      { tag: "cv09", name: "Flat-top three" },
      { tag: "cv10", name: "Capital G with spur" },
      { tag: "cv11", name: "Single-story a" },
      { tag: "cv12", name: "Compact f" },
      { tag: "cv13", name: "Compact t" },
      { tag: "cv14", name: "Alternate capital sharp S" },
      { tag: "ss01", name: "Open digits" },
      { tag: "ss02", name: "Disambiguation" },
      { tag: "ss03", name: "Round quotes & commas" },
      { tag: "ss04", name: "Disambiguation (no slashed zero)" },
      { tag: "ss05", name: "Circled characters" },
      { tag: "ss06", name: "Squared characters" },
      { tag: "ss07", name: "Square punctuation" },
      { tag: "ss08", name: "Square quotes" },
    ],
  },
  "JetBrains Mono": {
    features: ["aalt", "calt", "case", "ccmp", "cv01", "cv02", "cv03", "cv04", "cv05", "cv06", "cv07", "cv08", "cv09", "cv10", "cv11", "cv12", "cv14", "cv15", "cv16", "cv17", "cv18", "cv19", "cv20", "cv99", "frac", "locl", "ordn", "sinf", "ss01", "ss02", "ss19", "ss20", "subs", "sups", "zero"],
    named: [
      { tag: "ss01", name: "Classic construction" },
      { tag: "ss02", name: "Closed construction" },
      { tag: "ss19", name: "Broken equals ligatures" },
      { tag: "ss20", name: "Rased bar f" },
    ],
  },
  "Monaspace Neon": {
    features: ["aalt", "calt", "case", "ccmp", "cv01", "cv02", "cv10", "cv11", "cv12", "cv13", "cv30", "cv31", "cv32", "cv33", "cv60", "cv61", "cv62", "dnom", "fina", "frac", "fwid", "init", "ital", "liga", "locl", "medi", "numr", "ordn", "rlig", "sinf", "ss01", "ss02", "ss03", "ss04", "ss05", "ss06", "ss07", "ss08", "ss09", "ss10", "subs", "sups"],
    named: [
      { tag: "ss01", name: "SS01: Equal Symbols" },
      { tag: "ss02", name: "SS02: Comparisons" },
      { tag: "ss03", name: "SS03: Arrows" },
      { tag: "ss04", name: "SS04: HTML Tags" },
      { tag: "ss05", name: "SS05: F# Shapes" },
      { tag: "ss06", name: "SS06: Markdown Strings" },
      { tag: "ss07", name: "SS07: Centered Colon" },
      { tag: "ss08", name: "SS08: Centered Period" },
      { tag: "ss09", name: "SS09: Double Arrows" },
      { tag: "ss10", name: "SS10: Other Tags" },
    ],
  },
};
